// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QXCVdC9idQrtxIyk20sG5QGBoKlRJBk',
    appId: '1:411395097074:web:eb9e011d24325dfa756b6b',
    messagingSenderId: '411395097074',
    projectId: 'flutter-lovers-41970',
    authDomain: 'flutter-lovers-41970.firebaseapp.com',
    storageBucket: 'flutter-lovers-41970.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGCRhTk-TRb2afuqWn2G-_F13O5-U4uGQ',
    appId: '1:411395097074:android:2fb6fa83c283909f756b6b',
    messagingSenderId: '411395097074',
    projectId: 'flutter-lovers-41970',
    storageBucket: 'flutter-lovers-41970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTmSpI9w8uQ4Yx2qcDwLJgk_Eg5WODFA',
    appId: '1:411395097074:ios:d7535fcdbed98b50756b6b',
    messagingSenderId: '411395097074',
    projectId: 'flutter-lovers-41970',
    storageBucket: 'flutter-lovers-41970.appspot.com',
    iosClientId: '411395097074-s3q79u9csdckhc9vht5nakbfmjbt2sva.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTmSpI9w8uQ4Yx2qcDwLJgk_Eg5WODFA',
    appId: '1:411395097074:ios:d7535fcdbed98b50756b6b',
    messagingSenderId: '411395097074',
    projectId: 'flutter-lovers-41970',
    storageBucket: 'flutter-lovers-41970.appspot.com',
    iosClientId: '411395097074-s3q79u9csdckhc9vht5nakbfmjbt2sva.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLovers',
  );
}
